### ISSUE TITLE
Error : ReflectionException in Container.php line 734: Class App\Http\Controllers\Admin\MenuItemCrudController does not exist

### ISSUE THREAD

**Issue by jpvdw86** [Laravel-Backpack/MenuCRUD#12]
I have installed as described, but somehow it would not work and I get the following message

ReflectionException in Container.php line 734:
Class App\Http\Controllers\Admin\MenuItemCrudController does not exist
what am I doing wrong?

**Comment by razlupercio** [comment]
hey, sorry to zombiefy this but I'm getting a similar issue with my project, what was the solution to your problem?

I'm getting the following error:

`ReflectionException in Container.php line 719:
Class App\Http\Controllers\MenuItemCrudController does not exist`

But I double checked and the class is there, I have no idea what's going on here...

**Comment by vipertecpro** [comment]
I think it's an issue of namespace: This worked for me
change
namespace Backpack\MenuCRUD\app\Http\Controllers\Admin;
to this
namespace App\Http\Controllers\Admin;

**Comment by tabacitu** [comment]
Yup,  I can confirm @vipertecpro  and @razlupercio . When you install MenuCRUD in your own project (not through composer install), you'll need to change the namespaces. It's step A3 from the installation. The classes will no longer live inside the Backapack namespace, but your app's namespace.

Hope it helps.
Cheers!

**Comment by schel4ok** [comment]
I have same error, but I changed the namespaces.

this is **MenuItemCrudController**
```
namespace App\Http\Controllers\Admin;

use Backpack\CRUD\app\Http\Controllers\CrudController;

class MenuItemCrudController extends CrudController
{
```


and this is the error
```
D:\OSPanel\home\myproject.dev>php artisan migrate

   INFO  Running migrations.

  2016_05_05_115641_create_menu_items_table ............................................................................... 65.92ms DONE


D:\OSPanel\home\myproject.dev>php artisan backpack:add-menu-content "<x-backpack::menu-item title='Menu' icon='la la-list' :link=\"backpack_url('menu-item')\" />"

   ReflectionException

  Class "Admin\MenuItemCrudController" does not exist

  at vendor\backpack\crud\src\app\Library\CrudPanel\CrudRouter.php:14
     10▕     public static function setupControllerRoutes(string $name, string $routeName, string $controller, string $groupNamespace = ''): void
     11▕     {
     12▕         $namespacedController = class_exists($controller) ? $controller : $groupNamespace.$controller;
     13▕
  ➜  14▕         $controllerReflection = new ReflectionClass($namespacedController);
     15▕         $setupRoutesMethod = $controllerReflection->getMethod('setupRoutes');
     16▕
     17▕         // check if method has #[DeprecatedIgnoreOnRuntime] attribute
     18▕         if (empty($setupRoutesMethod->getAttributes(\Backpack\CRUD\app\Library\Attributes\DeprecatedIgnoreOnRuntime::class))) {

  1   vendor\backpack\crud\src\app\Library\CrudPanel\CrudRouter.php:14
      ReflectionClass::__construct("Admin\MenuItemCrudController")

  2   vendor\backpack\crud\src\macros.php:190
      Backpack\CRUD\app\Library\CrudPanel\CrudRouter::setupControllerRoutes("menu-item", "menu-item", "MenuItemCrudController", "Admin\")
```
