### ISSUE TITLE
url method problem if internal link is null

### ISSUE THREAD

**Issue by frankar** [Laravel-Backpack/MenuCRUD#13]
in MenuItem.php I suggest:

            case 'internal_link':
                return is_null($this->link) ? "#" : url($this->link);
                break;

because if the internal_link is not compiled when you render it, you has this error:
htmlspecialchars() expects parameter 1 to be string, object given

**Comment by tabacitu** [comment]
Hi @frankar,

Thank, just pushed the fix.

Cheers!

**Comment by frankar** [comment]
Great!!

Il 05/apr/2017 14:27, "Cristian Tabacitu" <notifications@github.com> ha
scritto:
