### ISSUE TITLE
Menu improvements

### ISSUE THREAD

**Issue by frankar** [Laravel-Backpack/MenuCRUD#14]
Is possible to lock menu item deletion if itself has childs ?

Can show in menu parent selection only items with depth less then max allowed ? 
..max allowed is defined in MenuItemController on line 22: $this->crud->enableReorder('name', 2)

**Comment by tabacitu** [comment]
Sorry to be so late to answer. You probably have had this figure out by now, but for posterity: yes, you can customize the delete functionality by overwriting the ```destory()``` method in your EntityCrudController:

```php
    /**
     * Remove the specified resource.
     *
     * @param int $id
     *
     * @return string
     */
    public function destroy($id)
    {
        $this->crud->hasAccessOrFail('delete');
        if (YOUR_CONDITION) {
          return $this->crud->delete($id);
        }
        
        return false;
    }
```

Cheers!
