### ISSUE TITLE
Reordering not working for sub-levels

### ISSUE THREAD

**Issue by reeslo** [Laravel-Backpack/MenuCRUD#15]
I can set order for sub and sub sub item to root level only

https://framadrop.org/r/CdKG-4kIju#hEyTtdWWdGevnxdtCUohef8bmInvBxb9lgnPrVFGwPM=

**Comment by tabacitu** [comment]
Hi @reeslo ,

Yes, by default the reordering is set to only allow a simple hierarchy. You can overwrite this by specifying the max_tree_lavel option in your CrudController: ```$this->crud->enableReorder('label_name', 9999);```

If you're using MenuCRUD as an installed package, it's probably quickest to just remove it from you composer.json and install it in your app folder, like the [installation option A here](https://laravel-backpack.readme.io/docs/menu-crud).

Cheers!

**Comment by reeslo** [comment]
Thank you very much
