### ISSUE TITLE
Requires Backpack/PageManager to use

### ISSUE THREAD

**Issue by nathanh0** [Laravel-Backpack/MenuCRUD#18]
Great product so far!

I did a clean install with Backpack for Laravel 5.3, following all steps, and included the as one of the steps MenuCRUD to manage menus.

When I went to click "Add Menu" from the Menu manager page, it gave me an error:

`Class '\Backpack\PageManager\app\Models\Page' not found`

I then went and looked for `composer require backpack/pagemanager`

**After that and publishing, MenuCRUD started working.**

**Comment by tabacitu** [comment]
Hi @nathanh0 ,

You're right. I just included it in composer.json.

Thanks, cheers!
