### ISSUE TITLE
Menu Item children relationship should have parent_id as the foreign_key

### ISSUE THREAD

**Issue by vishalbhide** [Laravel-Backpack/MenuCRUD#2]
The below error is displayed when I try to access a menu item's children function -

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'menu_items.menu_item_id' in 'where clause' (SQL: select * from `menu_items` where `menu_items`.`menu_item_id` = 1 and `menu_items`.`menu_item_id` is not null) 

In order to fix it, please assign 'parent_id' as the foreign key in the children function

Change from - 
```
public function children()
{
  return $this->hasMany('Backpack\MenuCRUD\app\Models\MenuItem');
}
```

Change To

```
public function children()
{
   return $this->hasMany('Backpack\MenuCRUD\app\Models\MenuItem', 'parent_id');
}
```

**Comment by tabacitu** [comment]
Thank you! You were right, it's fixed now.
