### ISSUE TITLE
elfinder route fix

### ISSUE THREAD

**Issue by AlexiaTorres** [Laravel-Backpack/MenuCRUD#24]
config/elfinder.php  
line 42 
'route' => [
        'prefix'     => config('backpack.base.route_prefix'**, 'admin')**.'/elfinder',
        'middleware' => ['web', 'admin'], //Set to null to disable middleware filter
    ],

**Comment by tabacitu** [comment]
Hi @AlexiaTorres ,

Thanks for the fix. Included it in Backpack\CRUD's dev branch, it will be available to everyone in the next point update.

Cheers!
