### ISSUE TITLE
Update example / readme to not hardcode the url to /admin

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/MenuCRUD#35]
We should do it the same way like on the other packages:

Instead of: 
`<li><a href="{{ url('admin/menu-item') }}"><i class="fa fa-list"></i> <span>Menu</span></a></li>`
should be something like:
`<li><a href="{{ url(config('backpack.base.route_prefix', 'admin') . /menu-item') }}"><i class="fa fa-list"></i> <span>Menu</span></a></li>`

Also, make the text something more obvious like "Menu Builder" instead of "Menu"

**Comment by tabacitu** [comment]
Changed! Thank you!
