### ISSUE TITLE
Make it extention & add support for multiple menus / view echo helper / multi-lang

### ISSUE THREAD

**Issue by cristianuibar** [Laravel-Backpack/MenuCRUD#36]
This should be an extension not a CRUD example and should support multiple menus, with the ability to quickly "echo" / output them in the views via a helper method using the current bootstrap template, with the ability to change the template as the user wants through a partial blade file.
Also, it would be super useful to support multi-languages by default like all the other backpack modules.

No idea how could we do it atm but it will for sure be something useful for the backpack environment.

**Comment by tabacitu** [comment]
Hi @cristianuibar , I agree - there are a lot of things we could improve about MenuCRUD. Right now it's just basic - a way to let the admin edit a menu you output on the front-end. I hope in time we'll get there :-)

Cheers!
