### ISSUE TITLE
Missing "pages" table after installing as a package

### ISSUE THREAD

**Issue by linuxiamo** [Laravel-Backpack/MenuCRUD#37]
Hi,

I installed this MenuCRUD following the indications in your readme section "Installation type (B) - package". After I run the site the first time, if I click on the button to add the first menu, I receive this error:

> ErrorException (E_ERROR)
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'mydb.pages' doesn't exist (SQL: select * from `pages`) (View: /Users/umberto/progetti/ctf5bp/vendor/backpack/crud/src/resources/views/fields/page_or_link.blade.php) 

What's wrong with this?

Thanks for any help you may give.

**Comment by linuxiamo** [comment]
Okay... it seems I found a solution by myself.

I created the "pages" table, copying the one that is in the database of the Backpack demo featuring all the various Backpack packages. Here the steps I followed.

On the Terminal run:
`php artistan make:migration create_pages_table --create=pages`

Then open the migration file in your editor, and type in:

```php
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreatePagesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // TODO: use JSON data type for 'extras' instead of string
        Schema::create('pages', function (Blueprint $table) {
            $table->increments('id');
            $table->string('template');
            $table->string('name');
            $table->string('title');
            $table->string('slug');
            $table->text('content')->nullable();
            $table->text('extras')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('pages');
    }
}
```
Finally run on Terminal:
`php artisan migrate`

And that's all. The create button now works as intended.

An alternative solution could be to inspect the MenuCRUD package and delete all the references and requests of the type of link known as "Page", from the Views files (I suppose...).

I hope this will help someone else.

Bye.

**Comment by ijpatricio** [comment]
Found the the same issue, came to open an issue, and found this one.
I figured it was the requirements missing.

Steps I did:
1 - add to config/app providers:
Backpack\PageManager\PageManagerServiceProvider::class,

2- php artisan vendor:publish --provider="Backpack\PageManager\PageManagerServiceProvider"

3- php artisan migrate

Hope this helps someone. 

I installed base, crud, and menudrud. by this order, so the package I added manually was still missing registration and configuration..

Happy coding!

**Comment by tabacitu** [comment]
Hi guys,

You are right, thank you for writing about this to help others. 

The reason this doesn't officially require [PageManager](https://github.com/Laravel-Backpack/PageManager) is because some users prefer NOT to use PageManager - they roll their own. But yes, the easiest way to fix this is to **install PageManager first, then MenuCRUD**. That's what most people should do.

Thanks, cheers!
