### ISSUE TITLE
Menu reorder issue

### ISSUE THREAD

**Issue by AurelDragut** [Laravel-Backpack/MenuCRUD#4]
Hi,

I am trying to reorder a menu and i get an error like:

[2016-09-07 09:34:36] local.ERROR: exception 'ErrorException' with message 'Undefined index: item_id' in /vendor/backpack/crud/src/PanelTraits/Reorder.php:25

i have 9 items but i see 10 in the Console Log and the first one has item_id as null.

What should be done here?

**Comment by tabacitu** [comment]
Hi Aurel,

If you're on Laravel 5.3 it's probably because Laravel 5.3 ships with MySQL strict=true,  whereas Laravel 5.2 did not. You can set it to false si config/database.php

**Comment by AurelDragut** [comment]
Thanks but it doesn't seem to be the solution. I did change to false in the config file but with no change in the outcome. I will change the ids in the db to get the order that i need until we get a solution to this. I guess i am the first onewith this issue, but i am curious if i am the only one and it could be a server issue.

**Comment by tabacitu** [comment]
Hi @AurelDragut ,

I've just updated Backpack/CRUD to account for MySQL strict mode ON. If you run a ```composer update``` and get Backpack/CRUD v3.1.2, it should fix the issue.

Cheers!

P.S. I'll go ahead and close this issue so we don't clog the section. Feel free to open it again if you encounter problems or comment if you have follow-ups.
