### ISSUE TITLE
How to use tabs menu in crud PanelTraits

### ISSUE THREAD

**Issue by wwkk123** [Laravel-Backpack/MenuCRUD#43]
Anyone please help to guide how to use tabs menu in laravel.

**Comment by tabacitu** [comment]
@wwkk123 , what do you mean? Please provide more details if you want someone to be able to help. What tabs menu? There are no tabs in Backpack\MenuCRUD. It only provides a quick way to create/update/delete/reorder menu items.

That being said, this does not look like a bug to me, so I'll close this issue. Happy to reply though, even I'll be closing the issue, so please reply here.

Cheers!
