### ISSUE TITLE
Trait 'App\PageTemplates' not found

### ISSUE THREAD

**Issue by anditsung** [Laravel-Backpack/MenuCRUD#47]
# Bug report

im installing this on backpack v4 with addon logmanager, permissionmanager, laravel-elfinder

when installing menucrud have this error

'''
iTsungAir:backpack4 anditsung$ composer require backpack/menucrud
Using version ^2.0 for backpack/menucrud
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
PHP Fatal error:  Trait 'App\PageTemplates' not found in /Users/anditsung/Work/backpack4/vendor/backpack/pagemanager/src/app/Http/Controllers/Admin/PageCrudController.php on line 17

In PageCrudController.php line 17:

  Trait 'App\PageTemplates' not found

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 25'''

after this everything is broken on backpack

**Comment by tabacitu** [comment]
True, this package needs [Backpack\PageManager](https://github.com/Laravel-Backpack/pagemanager) to be installed first. I've added a note to the installation docs. Thank you @anditsung !
