### ISSUE TITLE
Facade\Ignition\Exceptions\ViewException htmlspecialchars() expects parameter 1 to be string, array given (View: /home/vagrant/code/vendor/backpack/crud/src/resources/views/crud/fields/page_or_link.blade.php)

### ISSUE THREAD

**Issue by brynnb** [Laravel-Backpack/MenuCRUD#50]
# Bug report

### What I did:

Installed fresh backpack per instructions and installed optional packages per instructions. Opened the new menu section and clicked "Add new menu item"

### What I expected to happen:

To render the "add menu item" page

### What happened:

Facade\Ignition\Exceptions\ViewException
htmlspecialchars() expects parameter 1 to be string, array given (View: /home/vagrant/code/vendor/backpack/crud/src/resources/views/crud/fields/page_or_link.blade.php)

![image](https://user-images.githubusercontent.com/1271817/66690922-c23a1200-ec82-11e9-9710-c713f40feb0d.png)

### What I've already tried to fix it:

https://github.com/Laravel-Backpack/MenuCRUD/commit/8b4e9b9d4780d72853caf80b9256dd4da6a14537#diff-4c0570cf6e95730105a00ba8cf5abd7b

Reverting this change fixed it

### Backpack, Laravel, PHP, DB version:

4, 6, PHP 7.3.9-1, 14.14

**Comment by tabacitu** [comment]
Hi @brynnb ,

That's weird. That change was specifically so it _would_ work 😄 It worked fine in my tests, so there should be a difference between my setup and yours. Do you have ```page_or_link.blade.php``` published by any chance? In your ```resources/views/vendor/backpack/crud/fields/````? If so, please copy-paste it here. Removing it should fix this for you (without the revert).

Cheers!

**Comment by brynnb** [comment]
The only page_or_link.blade is the one in `vendor/backpack/crud/src/resources/views/fields/page_or_link.blade.php`

Not sure what the difference is between our environments!

**Comment by tabacitu** [comment]
Oh I mean difference between what we installed and how (using composer), not our env. That shouldn't matter.

Hmmm... ok then... what does ```php artisan backpack:version``` output?

**Comment by brynnb** [comment]
`Command "backpack:version" is not defined.`

Here's the relevant part of the composer file:

"require": {
        "php": ">=7.1.3",
        "laravel/framework": "5.8.*",
        "fideloper/proxy": "^4.0",
        "backpack/crud": "3.6.*",
        "backpack/logmanager": "^2.3",
        "backpack/settings": "^2.0",
        "backpack/pagemanager": "^1.1",
        "backpack/menucrud": "^1.0",
        "backpack/newscrud": "^2.1",
        "backpack/permissionmanager": "4.0.*",
        "spatie/laravel-translatable": "^3.0",
        "barryvdh/laravel-elfinder": "^0.4.2",
        "spatie/laravel-backup": "^6.1",
        "backpack/backupmanager": "1.4.*",
        "fzaninotto/faker": "~1.4",
        "mpociot/versionable": "~3.0"
    },

**Comment by brynnb** [comment]
Woops, ignore previous comment. Was running in the wrong project. Here's the output:

### PHP VERSION:
PHP 7.3.9-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 12:54:24) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

### LARAVEL VERSION:
laravel/framework                     v6.0.4     The Laravel Framework.

### BACKPACK VERSION:
backpack/backupmanager                2.0.0      Admin interface for managing backups in Backpack, on Laravel 5.2+
backpack/crud                         4.0.5      Quickly build an admin interfaces using Laravel 6, CoreUI, Boostrap 4 and jQuery.
backpack/generators                   2.0.4      Generate files for laravel projects
backpack/logmanager                   3.0.0      An interface to preview, download and delete Laravel log files.
backpack/pagemanager                  2.0.1      Create admin panels for presentation websites on Laravel, using page templates and Backpack\CRUD.
backpack/permissionmanager            5.0.1      Users and permissions management interface for Laravel 5 using Backpack CRUD.
backpack/settings                     3.0.0      Application settings interface for Laravel 5 using Backpack CRUD.

**Comment by tabacitu** [comment]
AHA! You're running CRUD 4.0.5 and the fix was pushed in 4.0.6 :-) A ```composer update``` should do it for you 😄

**Comment by brynnb** [comment]
Good catch, that fixed it. Thanks! Hopefully this is useful for anyone else who might run into this problem.
