### ISSUE TITLE
steal the menu generator from voyager

### ISSUE THREAD

**Issue by starcevpro** [Laravel-Backpack/MenuCRUD#58]
steal the menu generator from voyager =c
voyager is bad, but it has a good menu generator

**Comment by tabacitu** [comment]
🤣  I appreciate the frankness @starcevpro . I haven't tried Voyager in a long _long_ time. Can you please provide a screenshot/smth, or tell us what in particular you like about it?

Cheeers!

**Comment by mahasadhu** [comment]
I've just made a PR quite similar to this https://github.com/Laravel-Backpack/MenuCRUD/pull/60

**Comment by tabacitu** [comment]
Excellent. Closing in favour of #60 - let's move the conversation there please.
