### ISSUE TITLE
Menu item in README

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/MenuCRUD#81]
Received this from a customer by email:

> Hi,
> I was trying to install MenuCRUD in v6 this morning using method B and it errored.
https://github.com/Laravel-Backpack/MenuCRUD#:~:text=%5Boptional%5D%20Add%20a%20menu%20item%20for%20it%20in%20resources/views/vendor/backpack/base/inc/sidebar_content.blade.php%20or%20menu.blade.php%3A
> In step 4, the command is still for Backpack v5 only `backpack:add-sidebar-content`. It should be replaced with the v6 command to avoid confusion.

--

Note that this is about METHOD B. @karandatwani92 can you please do that in this repo and double-check any other repos that have both Method A and Method B (the ones with CRUD in the name)?

Thanks!

**Comment by karandatwani92** [comment]
NEED TO UPDATE:

- [ ] https://github.com/Laravel-Backpack/MenuCRUD
- [ ] https://github.com/Laravel-Backpack/NewsCRUD
- [ ] https://github.com/Laravel-Backpack/activity-log
