### ISSUE TITLE
Update on a Menu-item - CheckValidity fails

### ISSUE THREAD

**Issue by Faber44** [Laravel-Backpack/MenuCRUD#84]
# Bug report
Form isn't submited on update with "page slug input" selected.

### What I've already tried to fix it:
HTML validation fails because of the attribute: required on disabled inputs (aka internal link input & external link input).
Moved the required attribute only where it belongs in crud>fields>page_or_llink.blade.php :

BEFORE :
```php
{{-- internal link input --}}
 <input
    type="text"
    class="form-control"
    placeholder="{{ trans('backpack::crud.internal_link_placeholder', ['url', url(config('backpack.base.route_prefix').'/page')]) }}"
    for="{{ $field['configurationNames']['link'] }}"
required
    @if(isset($entry))
        @if ($entry->{$field['configurationNames']['type']} !== 'internal_link' && $entry->{$field['configurationNames']['type']} !== 'page_link')
            disabled="disabled"
        @endif
  
        @if ($entry->{$field['configurationNames']['type']} === 'internal_link' && $entry->{$field['configurationNames']['link']})
            value="{{ $entry->{$field['configurationNames']['link']} }}"
        @endif
    @else
        disabled="disabled"
    @endif
   >
``` 

AFTER :
```php
<input
    type="text"
    class="form-control"
    placeholder="{{ trans('backpack::crud.internal_link_placeholder', ['url', url(config('backpack.base.route_prefix').'/page')]) }}"
    for="{{ $field['configurationNames']['link'] }}"
    @if(isset($entry))
        @if ($entry->{$field['configurationNames']['type']} !== 'internal_link' && $entry->{$field['configurationNames']['type']} !== 'page_link')
            disabled="disabled"
        @endif

        @if ($entry->{$field['configurationNames']['type']} === 'internal_link' && $entry->{$field['configurationNames']['link']})
            value="{{ $entry->{$field['configurationNames']['link']} }}"
required
        @endif
    @else
        disabled="disabled"
    @endif
    >
``` 
### Backpack, Laravel, PHP, DB version:
Backpack 6
Laravel 10
Php 8.2
MariaDB 10.6.5

**Comment by jcastroa87** [comment]
Hello @pxpm we have a problem here.

When we added a "Page Link" type Menu item, we came back to just updating the link. there is a problem that prevented the update.

<img width="1426" alt="image" src="https://github.com/Laravel-Backpack/MenuCRUD/assets/44643608/f4085150-8863-4d4e-a160-6d5659454367">

Please let me know if you need further information.

Cheers.

**Comment by danielwaghorn** [comment]
This continues to be an issue with the package, and is essentially narrowed down to the `page_or_link` field type based on our testing.

The typical resolution on our side for this on projects it to override the `page_or_link.blade.php` template by copying it to `resources/views/vendor/backpack/crud/fields/page_or_link.blade.php` and removing the `required` attribute from all instances of `.form-control`.

**Comment by pxpm** [comment]
Thanks for the report, and sorry for the time it took to come back here and fix this. 🙏 

Let us know if you are still experiencing issues 👍 

Cheers
